apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer100
  name: consumer100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer100
  template:
    metadata:
      labels:
        app: consumer100
    spec:
      containers:
        - name: consumer100
          image: docker.io/mezzeddine/consumerbin:v6
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLEEP
              value: "10"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=500